# Generated by Django 2.2.2 on 2020-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=250)),
                ('option1', models.TextField(max_length=50)),
                ('option2', models.TextField(max_length=50)),
                ('option3', models.TextField(max_length=50)),
                ('option4', models.TextField(max_length=50)),
            ],
        ),
    ]
