# Generated by Django 2.2.2 on 2020-04-06 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
