# Generated by Django 2.2.2 on 2020-04-05 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
