# Generated by Django 2.2.2 on 2020-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0002_quiz_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
