# Generated by Django 2.2.2 on 2020-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0003_quiz_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
